- name: write out watcher config file
  template: >
    src=edx/app/xqwatcher/xqwatcher.json.j2
    dest={{ xqwatcher_conf_dir }}/xqwatcher.json
    mode=0644 owner={{ xqwatcher_user }} group={{ xqwatcher_user }}
    
- include: deploy_watcher.yml
  tags:
    - deploy-watcher

- include: deploy_courses.yml
  tags:
    - deploy-courses